In [38]:
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [39]:
X,y = load_diabetes(return_X_y=True)

In [40]:
# X

In [41]:
print(X.shape)

(442, 10)


In [42]:
print(y.shape)
# y

(442,)


In [43]:
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [44]:
x_train.shape

(353, 10)

In [45]:
x_test.shape

(89, 10)

In [46]:
reg = LinearRegression()

In [47]:
reg

LinearRegression()

In [48]:
reg.fit(x_train,y_train)

LinearRegression()

In [49]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [50]:
reg.intercept_

151.88331005254167

In [51]:
y_pred=reg.predict(x_test)

In [52]:
r2_score(y_test,y_pred)

0.4399338661568969

In [66]:
class BGDRegression:

    def __init__(self,lr=0.1,epoche=100):
        self.lr=lr;
        self.epoche=epoche;
        self.coef_=None
        self.intercept_ = None
    def fit(self,x_tain,y_tain):
        self.intercept_=0
        self.coef_ = np.ones(x_train.shape[1])
        print(self.coef_)
        for i in range(self.epoche):
            y_hat = np.dot(x_train,self.coef_) + self.intercept_
            # calculate the intercept value
            # intercept_der = -2*np.mean(yi-yi_hat)
            intercept_der = -2*np.mean(y_train - y_hat)
            self.intercept_ = self.intercept_ - (self.lr * intercept_der)
            # calculating the coeficient
            coef_der = -2*np.dot((y_train - y_hat), x_train)//x_train.shape[0]
            self.coef_ = self.coef_ - (self.lr * coef_der)
    def predict(self,x_test):
        return np.dot(x_test,self.coef_)+ self.intercept_


In [73]:
gd = BGDRegression(0.1,50)

In [74]:
gd.fit(x_train,y_train)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [75]:
y_pred = gd.predict(x_test)

In [76]:
y_pred

array([151.84411041, 155.33167776, 150.51014816, 146.48695732,
       158.80004988, 157.50335678, 144.94646426, 145.79140094,
       143.93749941, 154.04396476, 154.07675975, 152.25793131,
       154.43014264, 152.44543498, 158.05767478, 145.86975683,
       152.64204005, 147.5877043 , 150.21339083, 149.87664288,
       146.31302533, 158.02287778, 153.84938326, 154.65926396,
       148.07219469, 157.34791694, 154.93888804, 150.2548007 ,
       141.57666265, 161.79817482, 159.32160575, 147.57527413,
       142.51377283, 147.82139671, 155.52680194, 152.21635233,
       153.36515068, 156.19208181, 146.95503759, 158.89793513,
       148.13634361, 148.64683585, 154.38512042, 154.22792626,
       151.93128367, 149.91454109, 153.42612698, 161.99129514,
       147.87240741, 157.62850102, 158.3492536 , 146.30705235,
       148.32521086, 152.77249543, 154.92580078, 148.0793085 ,
       154.28793451, 144.56045101, 151.44040529, 148.04314426,
       152.14524623, 154.20041   , 147.50892   , 154.36

In [77]:
r2_score(y_test,y_pred)

0.059306817446813875